#!/bin/csh -f

#the following adds the idl procedures
setenv IDL_STARTUP ~/Desktop/gdl/idl_startup.pro

#set to the location of the bin directory of gdl
if ($#argv != 0) then 
	if ($argv[1] == 'gdl') then 
		echo 'Using GDL'
		setenv IDL_DIR /opt/local/
		setenv IDL_PATH /Applications/itt/idl/lib
		#this next line adds the GDL-specific functions
		#this setting is specific to your GDL installation and may work with no change for a macports installation
		setenv IDL_PATH $IDL_PATH{:}+/opt/local/share/gnudatalanguage/lib
	endif
else 
	echo 'Using IDL'
endif

## SSW Settings
### set the location of your SSW install
setenv SSW /Users/schriste/ssw
setenv SSW_INSTR "gen"
source $SSW/gen/setup/setup.ssw /quiet

$SSW/gen/setup/ssw_idl
